import {
  Waves, Moon, Sun, Menu, X, Car, Zap, Droplets,
  Smartphone, Star, Shield, Rocket, MapPin, Phone,
  Mail, Clock, ChevronDown, ChevronUp, CheckCircle,
  ArrowRight, MessageCircle, Package, Shirt, Sparkles,
  Calendar, Truck,
} from "lucide-react";

export const icons = {
  waves: Waves,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  close: X,
  car: Car,
  zap: Zap,
  droplets: Droplets,
  smartphone: Smartphone,
  star: Star,
  shield: Shield,
  rocket: Rocket,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  clock: Clock,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  checkCircle: CheckCircle,
  arrowRight: ArrowRight,
  messageCircle: MessageCircle,
  package: Package,
  shirt: Shirt,
  sparkles: Sparkles,
  calendar: Calendar,
  truck: Truck,
};