import {
  Waves,
  Moon,
  Sun,
  Menu,
  X,
  Car,
  Zap,
  Droplets,
  Smartphone,
  Star,
  Shield,
  Rocket,
  MapPin,
  Phone,
  Mail,
  Clock,
  ChevronDown,
  ChevronUp,
  CheckCircle,
  ArrowRight,
  MessageCircle,
  Package,
  Shirt,
  Sparkles,
  Calendar,
  Truck,
} from "lucide-react";

// Font Awesome icons from react-icons
import {
  FaHome,
  FaPhone,
  FaEnvelope,
  FaCar,
  FaShieldAlt,
  FaRocket,
  FaMapMarkerAlt,
  FaClock,
  FaCheck,
  FaStar,
  FaBox,
  FaTruck,
  FaCalendar,
  FaBars,
  FaTimes,
  FaSun,
  FaMoon,
  FaPhone as FaPhoneAlt,
  FaArrowRight,
  //FaMessage,
  FaSpinner,
  FaQuestion,
  FaServicestack,
  FaFacebook,
  FaTwitter,
  FaInstagram,
  FaWhatsapp,
} from "react-icons/fa";

export const icons = {
  // Lucide icons
  waves: Waves,
  moon: Moon,
  sun: Sun,
  menu: Menu,
  close: X,
  car: Car,
  zap: Zap,
  droplets: Droplets,
  smartphone: Smartphone,
  star: Star,
  shield: Shield,
  rocket: Rocket,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  clock: Clock,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  checkCircle: CheckCircle,
  arrowRight: ArrowRight,
  messageCircle: MessageCircle,
  package: Package,
  shirt: Shirt,
  sparkles: Sparkles,
  calendar: Calendar,
  truck: Truck,

  // Font Awesome icons
  faHome: FaHome,
  faPhone: FaPhone,
  faEnvelope: FaEnvelope,
  faCar: FaCar,
  faShield: FaShieldAlt,
  faRocket: FaRocket,
  faMapMarker: FaMapMarkerAlt,
  faClock: FaClock,
  faCheck: FaCheck,
  faStar: FaStar,
  faBox: FaBox,
  faTruck: FaTruck,
  faCalendar: FaCalendar,
  faBars: FaBars,
  faTimes: FaTimes,
  faArrowRight: FaArrowRight,
  // faMessage: FaMessage,
  faSpinner: FaSpinner,
  faQuestion: FaQuestion,
  faFacebook: FaFacebook,
  faTwitter: FaTwitter,
  faInstagram: FaInstagram,
  faWhatsapp: FaWhatsapp,
};
